### ISSUE TITLE
Linking to Instructions from Other Recipes

### ISSUE THREAD

**Issue by noorka** [lizziehop/reading-cookbooks#10]
How do we want to encode references to instructions from previous recipes? For example "Banana Syrup" says to follow the instructions for "Apricot Syrup" that was referenced previously in the chapter. Surround with the `<name>` tag and have the xml:id for the reference recipe? Maybe a pointer `<ptr>` or a reference `<ref>` (from [linking, segmentation, and alignment](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SAPTEG))?

**Comment by lizziehop** [comment]
How about:

To make this recipe for banana syrup, first follow the instructions for `<ptr target="xml:idofapricotsyrup">Apricot Syrup</ptr>`

**Comment by noorka** [comment]
If there is just the recipe title referenced put the `ptr` around that, if it says see recipe put the `ptr` around that.
