### ISSUE TITLE
Encoding all caps

### ISSUE THREAD

**Issue by Eliora-Horst** [lizziehop/reading-cookbooks#12]
The front matter includes several portions where the words are in all caps - should we encode that all caps, or just leave it in all caps as it already is?

**Comment by Eliora-Horst** [comment]
Solution - yes, include a rendition on the portion that is in all caps.

**Comment by noorka** [comment]
To be consistent we will use rend on an element. Use whatever is the most descriptive element (ie `<name>` or `<title>`) if no such element exists then use `<hi>`.
