### ISSUE TITLE
New XML IDs

### ISSUE THREAD

**Issue by PrakrutiM** [lizziehop/reading-cookbooks#3]
How should an XML:id be formatted for something that has an apostrophe in its name? E.g. Is it okay to format the id in the following manner for a recipe with the name "The Gardener's Wife Salad'? -> pic22.35_the_gardeners_wife_salad

**Comment by PrakrutiM** [comment]
for the ingredient tag, should the type be given in plural or singular? E.g. <ingredient type="eggs"> OR <ingredient type="egg">?

**Comment by noorka** [comment]
> How should an XML:id be formatted for something that has an apostrophe in its name? E.g. Is it okay to format the id in the following manner for a recipe with the name "The Gardener's Wife Salad'? -> pic22.35_the_gardeners_wife_salad

Remove apostrophes('), but keep hyphens (-).

**Comment by noorka** [comment]
> for the ingredient tag, should the type be given in plural or singular? E.g. OR ?

Ingredient types will all be singular.
