### ISSUE TITLE
Recipe as Ingredients

### ISSUE THREAD

**Issue by PrakrutiM** [lizziehop/reading-cookbooks#4]
How should a recipe that's being treated as an ingredient be encoded? On p158, for anchovy salad, a "Plain French Dressing" is listed as an ingredient. Should i use ingredient and measure tags or just use the recipe-addition attribute under the div tag?

**Comment by noorka** [comment]
Recipes that are ingredients should be tagged as an ingredient, but with the corresp attribute rather than a type 
`<ingredient corresp="#pic4.3_french_dressing">French Dressing</ingredient> <!- this is not the real xml:id-->`
