### ISSUE TITLE
Using the <name> tag

### ISSUE THREAD

**Issue by PrakrutiM** [lizziehop/reading-cookbooks#5]
When using the <name> tag, shoud we be capturing the whole description or just words like "Creole"? For example, in the section "...from the lips of the old Creole negro cooks" should the tag just be on "Creole", or on the whole phrase "old Creole negro cooks"?

**Comment by noorka** [comment]
Name should only surround "creole". We will discuss how we want to add the contextual notes to capture the rest of this during round two of encoding.
