### ISSUE TITLE
Encoding persName

### ISSUE THREAD

**Issue by PrakrutiM** [lizziehop/reading-cookbooks#8]
Should the who ="initials" be used in the persName under the <respStmt>
 `<resp>Transcription` by</resp> and first round encoding tags in the header?

**Comment by PrakrutiM** [comment]
`<publisher>Elizabeth Hopwood and The Center for Textual Studies and Digital Humanities</publisher>` should persName go around Elizabeth Hopwood?

**Comment by noorka** [comment]
In the responsibility statement `<respStmt>` you'll want to use the full name of the responsible person. In the revision description `<revisionDesc>` you'll want to use your initials as the @who attribute. If we make a personography we'll probably use our initials as our xml:ids. 

We should put the initials we use next to our name in the wiki too.
